### ISSUE TITLE
genomewide_labels should also output which peak a label comes from

### ISSUE THREAD

**Issue by amtseng** [kundajelab/seqdataloader#18]
When generating binary labels, it would also be useful for each bin to record what peak it comes from. This could be recorded as 4 additional columns: the peak file listed in the task list, and the coordinate of the peak itself.

**Comment by annashcherbina** [comment]
added in, use flag `--save_label_source` to generate output data frame with label_source prefix containing source peaks  for each task/bin https://github.com/kundajelab/seqdataloader/blob/master/examples/labelgen/save_source_labels_in_labelgen.sh
